### ISSUE TITLE
pAI - Attempts to use an invalid emote when clicking on someone

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora-Old#413]
Playing as a pAI, the following appears when clicking on a nearby character while in a mobile cat chassis (Currently untested with the other types of chassis):

Unusable emote 'nuzzles <Insert target's name here>'. Say *help for a list.

**Comment by skull132** [comment]
It's a line of code that runs along the lines of:
> M.emote("[M.friendly] [src]")

Most usually, it's called up with the attack_animal() proc, which is lacking a modification in pai.dm. Need to figure out which proc specifically it calls out when a pAI tries to mess with a human, as I doubt it's attack_animal().
