### ISSUE TITLE
Diona Decapitation Death

### ISSUE THREAD

**Issue by Conspire2Ignite** [Aurorastation/Aurora-Old#432]
A decapitated Diona does not turn into a nymph (or nymph-alien hybrid thing) but instead the camera focuses on the head and you get "You can almost hear someone talking" logs.

**Comment by Jamini** [comment]
Is this supposed to be a thing?
Because this sounds awesome as a thing.
If it isn't a bug, we should do it anyway.

**Comment by SoundScopes** [comment]
Yes, when a Diona died it used to become a nymph that would start a new. A bug back that was that it would pull a random ghost from from the list and kick the old player out of the game.
