### ISSUE TITLE
Open tags in signature code propogate

### ISSUE THREAD

**Issue by Jamini** [Aurorastation/Aurora-Old#443]
An open tag in a signature propagates through the setup screen 

http://i.imgur.com/EkGeFeV.png

How to replicate
1. Go to character setup
2. Edit your signature
3. Leave an open tag in your signature. I.E. "< i>SKRELLIAN DUBSTEP"

**Comment by skull132** [comment]
Going with an easy bypass of making it strip HTML input for the text, but with stylized modifications available over a selection (much like on a forum, actually).
