### ISSUE TITLE
Black security jumpsuit cannot be rolled down

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora-Old#450]
The 'roll Down Jumpsuit' verb does not work on the black Security Officer's Jumpsuit available in the officer lockers. This works for all the other jumpsuits I have tried it with so far.

**Comment by Serveris** [comment]
This isn't a bug as as it is laziness at the hands of baystation developers. Lots of alternative uniforms/jumpers can't be rolled down. I can look into throwing some together for security wear.

**Comment by SueTheCake** [comment]
Some are intended not to roll down, namely clothes that would make no sense - the black uniform appears to be pants and a shirt, not a jumpsuit, despite it being named as such.

**Comment by SierraKomodo** [comment]
Could an alternative to that be shirtless, then? Pants only? ICly, I have a character that wears as little layers as possible, particularly shirt wise because of the webbing vest and armor he has to wear, to keep himself from getting too hot (Tajarran)

**Comment by Serveris** [comment]
My solution will pretty much be just that. Characters can wear the black compression top undershirt if they want to roll this down for a plain black shirt.
