### ISSUE TITLE
Grass tiles don't extract seeds, and most plants lose sprites when harvestable

### ISSUE THREAD

**Issue by BlueSp34r** [Aurorastation/Aurora-Old#475]

**Comment by skull132** [comment]
Any chance of a list of plants that lose sprites past a certain point?

**Comment by BlueSp34r** [comment]
I know poppies and chilis, but I can't remember anything else. Need to play botany again to find out.

**Comment by BadLemonsXI** [comment]
Off the top of my head. TowerCaps, Penuts, Mushrooms and graps all have/seem to have, a missing image.
