### ISSUE TITLE
Our custom Drinks

### ISSUE THREAD

**Issue by DeaTacita** [Aurorastation/Aurora-Old#491]
The drinks Dalek added quite awhile ago are somewhat messy. 

Puossee Cafe - 1.     Should be Pousse Cafe
        2.     Should be 5 units Brandy, 5 Units Green Chartreuse, 5 Units White Creme de Menthe, 5 units Creme de Yvette, 5 units Yellow Chartreuse and 5 units Grenadine syrup
Currently is missing Creme de Yvette

John Collins - 1. Should be 10 units Whiskey Soda, 5 units Lemon Juice, 5 units Grenadine Syrup, 5 units Ice.  Currently Doesn't work. 

Metropolitan - 1. Should be 5 units Brandy, 5units Vermouth, 5 units Grenadine Syrup. Currently Doesn't work. 
        2. Doesn't have an icon.

Old Fashioned - 1. Should be  5 of Gin, 5 of Curaco and 5 of Ice - Currently Doesn't work.   

Rusty Nail - 1. Should be 5units of Whiskey, 5 of Drambuie. Currently doesn't work.

**Comment by Serveris** [comment]
Old fashioned works. Ordered that on the server yesterday, and it worked, proper icon and everything.

**Comment by SoundScopes** [comment]
The fix for the recipe was uploaded yesterday and it never had an icon missing.
