### ISSUE TITLE
AI Traffic Control Computer Bug

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora-Old#493]
If an AI is modifying NTSL code through the Telecommunications Traffic Monitor terminal, and they move their camera out of sight of the monitor, if they attempt at apply, compile, or execute their code, they recieve an error message stating they cannot exit out of the window while modifying code.

More importantly, after this occurs they cannot modify code until the monitor is dismantled and then reconstructed, which requires an engineer with all access to teleport up, disable the turrets, dismantle the monitor and reconstruct it.

**Comment by SoundScopes** [comment]
This comes from something that ensures only 1 person can edit the code at a time.
When you don't close the screen or detach from the console, everyone gets locked out.

**Comment by LordFowl** [comment]
I understand that. However, once you close the screen after receiving the error message as the AI, you can never access the NTSL coding window again, unless the entire monitor is deconstructed and reconstructed.
