### ISSUE TITLE
Borg EMP radio bug

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora-Old#503]
After a borg has been hit by an EMP special channels such as security or engineering no longer work. The only fix currently is respawning the player.

**Comment by SoundScopes** [comment]
Unable to replicate, what are the situations which the channel becomes inactive? What kind of EMP did you get hit by?

I tested using natual & admin spawned EMP's and each time I managed to get the security channel back within 15-20 second.

**Comment by darkrising** [comment]
The first EMP I got hit by was the station's black hole as an engineering bot and the 2nd time was caused by a hand held EMP when I was playing as a security bot. 

Both incidents caused the special channel in each case to be unusable even after 20 seconds.

**Comment by SierraKomodo** [comment]
I can say this has happened to me, once, several months ago when  Iwas first playing s Katana Bravo. The EMP came from the singularity in this scenario, iirc.

**Comment by jack-fractal** [comment]
I think in these cases your radio component may have been _broken_. In that case, replacing the radio might have fixed it.
