### ISSUE TITLE
Drone Disposals Transport Teleportation

### ISSUE THREAD

**Issue by EClef** [Aurorastation/Aurora-Old#507]
Today, around 12:15-19 PM Central Time, I was playing a drone and attempted to use the disposal unit behind the bar to go to the RD's office. It got me there, but I took a few steps towards the door and then teleported back to the disposal unit behind the bar.

Couldn't reproduce this. The second time I tried it, it worked normally.

**Comment by SoundScopes** [comment]
if you leave the window for the disposal unit open and walk around, for some reason if you walk into anything you teleport back to the location the disposal unit is at.

A temp fix is to make sure the window is closed.

**Comment by SoundScopes** [comment]
Another note, this is not just drones, it works with any mob that can use the disposal bin
