### ISSUE TITLE
Sleeves not rolling

### ISSUE THREAD

**Issue by Sgtsammac** [Aurorastation/Aurora-Old#526]
Since the Bluesec update the sleeve rolling on my custom item jumpsuit (Naval Working Uniform - Stevens Uniform) has stopped working.

Possibly for the same reason that the sprites don't exist for the ERT Backpack variants?

**Comment by GlamourChariot** [comment]
This has to do with how custom items have been changed to function using their own separate .dmi files rather than being compiled into a "custom item masterfile". 

Due to how it functions, it seems to be unable to recognize rolled up sleeves / rolled down jumpsuits.
