### ISSUE TITLE
Becoming Mouse: Death Timer

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora-Old#530]
If you die as a mouse, then ghost, and go back into your corpse... the timer for respawning as a mouse will completely reset. A bit annoying, but pretty minor.

**Comment by OneOneThreeEight** [comment]
Wasn't this just fixed?

**Comment by skull132** [comment]
It was reset the other way. You used to be able to bypass the respawn timer by doing this, now you're just getting to wait 30 minutes again.
