### ISSUE TITLE
Flamethrowers and spilled fuel don't combust properly

### ISSUE THREAD

**Issue by Keinto** [Aurorastation/Aurora-Old#531]

**Comment by EvilBrage** [comment]
Fire in general doesn't work properly.

**Comment by skull132** [comment]
After some reading, it turns out that our upstream branch has fuel fires disabled. Basically: they don't work on BS12, and they don't work here either, as a result. Will be working on a correction to fit our desires soon.

**Comment by Zuhayr** [comment]
Recently fire got reenabled and tweaked on dev, might be worth hunting those commits down. Alternatively wait until this staging period is over.

**Comment by Keinto** [comment]
Great to hear!
