### ISSUE TITLE
Some of the colored jumpsuits cannot have their sleeves rolled up despite the option being there.

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora-Old#533]

**Comment by MagmaRam** [comment]
Can anyone provide more details on this? Which jumpsuits it is, what happens when the verb is pressed? It seems most likely to be a sprite issue or sprite states not being referenced properly.

**Comment by Fortport** [comment]
Alright, let me finally respond to this. I will take screenshots of all of the jumpsuits that are having this problem and then link them below to help with this issue.

![3be5fe96b6aaf049df30a348db6b85c2](https://cloud.githubusercontent.com/assets/12206154/10906268/b9e6d392-81e5-11e5-886f-693a0e545681.png)

Yellow jumpsuit after you select the Roll Up Sleeves verb. As you can see, these sleeves aren't rolled.

![c3d6910940d53b2e98118c609621a51f](https://cloud.githubusercontent.com/assets/12206154/10906299/f6ed5310-81e5-11e5-853e-c1baabe838b2.png)

Just like the yellow jumpsuit, the green jumpsuit doesn't have sleeves that are rolled when you select Roll Up Sleeves.

![92cc9a38e5ad71b42b3d1a009cd017b0](https://cloud.githubusercontent.com/assets/12206154/10906331/4582f66a-81e6-11e5-9cd2-1572e6d35c17.png)

This is the blue jumpsuit. Same thing as the other two, yep-yep.


![1b853ebc41f303d525167288411b4d77](https://cloud.githubusercontent.com/assets/12206154/10906372/9ddde7c0-81e6-11e5-8010-63be77f437e9.png)


The pink jumpsuit suffers from the same problem as well.

**Comment by Fortport** [comment]
![4074309a95aea26176424c8109f7dc1d](https://cloud.githubusercontent.com/assets/12206154/10906422/f7fbfeae-81e6-11e5-8bee-8797e77e2d2f.png)

Forgot the black one.

**Comment by SierraKomodo** [comment]
Most likely a case of a missing sprite; I'd have to do a bit of digging to make sure though.

**Comment by Fortport** [comment]
It's easy enough to test out, yeah. Just go grab a jumpsuit.
