### ISSUE TITLE
Remove Handcuff-Breaking for Unathi

### ISSUE THREAD

**Issue by EvilBrage** [Aurorastation/Aurora-Old#535]
Simply put - removing the lines below (635-638) in  [Aurora/code/modules/mob/living/living.dm] should remove the undesired effect listed above.

```
        else if(istype(CM,/mob/living/carbon/human))
            var/mob/living/carbon/human/H = CM
            if(H.species.can_shred(H))
                can_break_cuffs = 1
```

**Comment by Zuhayr** [comment]
It will also remove cuffbreaking entirely, meaning that xenomorphs and vox raiders won't be able to proc it. You would be better off redefining Unathi can_shred() to return 0.

**Comment by EvilBrage** [comment]
Well, not entirely - hulks would still be able to do it - but that's a more elegant solution, I agree.
