### ISSUE TITLE
List of some sources for click delay procs that create massive amounts of spamlogs

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora-Old#548]
Pushing walls

Binning any mob, dead or alive, into a disposal unit

Knocking on windows

Kicking the glass case for the antique laser gun

Throwing mobs, dead or alive, anywhere.

Cult rune activation has no delay, either.

Will provide updates as I encounter them.

**Comment by SoundScopes** [comment]
I'm just removing the change that caused this to happen, there was no need for the change to be made, and even more so considering it wasn't ported properly.

**Comment by skull132** [comment]
Still missing checks for:
* anything grab related
* feeding people
