### ISSUE TITLE
You cannot write on a piece of paper/stamp it with a photo attached to it.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora-Old#563]
As title states.

You cannot use a pen on a piece of paper with a photo attachment to it. It's more of a low priority quality of life change, but it would be much appreciated if there was a code workaround for it.

**Comment by MagmaRam** [comment]
It seems to be that paper bundles in general can't be written on, and attaching a photo to a paper makes it a paper bundle, with one page being the photo.
