### ISSUE TITLE
Carpotoxin is not dealing toxin damage when consumed.

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora-Old#608]
Carpotoxin is not dealing toxin damage when consumed, so, you can eat space carp meat and don't get intoxicated.

**Comment by skull132** [comment]
I am not getting this bug. Toxpwr for carpotoxin is defined, and the on_mob_life proc is edited properly. I'll probably have to do some testing once I get home.

**Comment by Concerned** [comment]
I'm not entirely sure, but I think this might be a reference to chefs with carp food.
If you have a certain amount of antitoxin in the food as well as the carp meat, people won't get sick.

**Comment by Alberyk** [comment]
In game, I had the carp fillet after cutting a dead carp with the kitchen knife and after eating it, no toxin damage at all. So, even eating raw carp meat, it seems to deal no toxin damage.

**Comment by skull132** [comment]
I just tested this on the server. Two pieces of carp fillet, and I'm well on my way to dying. The toxin in pure form also works.

Could you tell me if you had eaten anything right before that, and what species you were?

**Comment by Alberyk** [comment]
I had nothing before, also, unathi.

**Comment by SoundScopes** [comment]
Were they holocarp?

**Comment by Alberyk** [comment]
No, carps spawned by random event, like the drones.
