### ISSUE TITLE
Diona nymphs, when 'scooped up', suffer oxygen deprivation (and death as a result).

### ISSUE THREAD

**Issue by ali-lali** [Aurorastation/Aurora-Old#610]
This happens when you select Merge With Gestalt, too, only you can't be put down again. I assume this is because part of the code for merging involves you getting 'scooped up' by the gestalt Diona.

**Comment by SoundScopes** [comment]
You shouldn't be held when merging with Diona's, that creates new problems of their own.
The breathing thing is an issue, and this happens whenever you pick up a mob. Simple animals like Runtime don't count.

**Comment by Zuhayr** [comment]
The issue will be that the relevant life check is attempting to retrieve air from the holder object. Should be able to define get_air() or whatever the proc is on the holder to get the air of the holder's turf. Alternatively, sync with Bay's updated holder code - monkeys and pAIs will be a bonus

**Comment by SoundScopes** [comment]
What are the changes that the monkeys and pAI's get?
