### ISSUE TITLE
Ejecting or firing a beanbag shell from a combat shotgun leaves behind a red shotgun shell

### ISSUE THREAD

**Issue by TishinaStalker** [Aurorastation/Aurora-Old#612]

**Comment by OneOneThreeEight** [comment]
Spent shells are red by default.

**Comment by TishinaStalker** [comment]
That's what I'm referring to, haha. Beanbag shells are green, but when you eject/fire them they turn red.

**Comment by SoundScopes** [comment]
Is this still an issue?

**Comment by TishinaStalker** [comment]
Checked on server the other day. This is no longer an issue and should be closed.
