### ISSUE TITLE
Joining with someone else's name causes records to be hijacked.

### ISSUE THREAD

**Issue by TheCritsyBear** [Aurorastation/Aurora-Old#622]
So, first is an issue Skull informed me to: Joining with someone else's name messes up the records.

Also, the person who joined with the name can't give things to the original, but they can give things to the new one.

And probably more interesting things! I know I forgot at least one.

**Comment by SoundScopes** [comment]
There a lot of things that this issue affects. I have to keep some secret as they are very powergamey.
Fixing this will involve changing how a lot of the game recognizes things. It may also be a byond limitation, we will see.

**Comment by TheCritsyBear** [comment]
I really like this new character I've created, but unfortunately it loses some magic if I can't copy people's names! This'd all be better if it wouldn't remove a " ' " before a name. Example: 'John Doe' turns into John Doe'. The first looks suspicious, while the second looks silly.
