### ISSUE TITLE
Genetics issues.

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora-Old#630]
While I haven't explored all the genetics powers yet, I have managed to locate Remote Viewing, and it seems to be a bit buggy.  You can use it, but it automatically ends after a seemingly random time.  I've seen the remove viewing last between 0.1 seconds (you return to yourself so fast it almost seems to not work) and 3 seconds.  On rare occasions, it lasts until you click remote viewing again, which I assume is how it's supposed to work.

**Comment by GlamourChariot** [comment]
Tested multiple times and it worked as intended every time on a local server, seems like this might need further testing on the live server.

**Comment by noghiri** [comment]
I can confirm it's acting strangely on live, it flashes up for a second or two and then shuts off.
