### ISSUE TITLE
Wearing a science jumpsuit as a skrell shows part of the body when facing the sides.

### ISSUE THREAD

**Issue by RustySh4ckleford** [Aurorastation/Aurora-Old#651]
http://gyazo.com/cb8263b813f050c2b113d63b785c8bf8
http://gyazo.com/e6a088f0dd90cd61eaad984eca3deb09

I don't know if this affects other sorts of jumpsuits as well.

**Comment by GlamourChariot** [comment]
Tested over several surfaces with a multitude of jumpsuits and wasn't able to duplicate, seems like a strange visual bug.

Has this happened to you consistently?
