### ISSUE TITLE
IPC Fur/Scales

### ISSUE THREAD

**Issue by Menown** [Aurorastation/Aurora-Old#663]
Getting your face sprayed as a Tajara'd IPC, ruins your hair. Changes the color, and ruins it. You can't get the hair back to normal without an admin's help to change the color back.

No idea if this applies to Unathi ones.

**Comment by LikelyMeowness** [comment]
Maybe a delay for the sprayer too, so a roboticist can't run up and ruin our day without a word.

**Comment by skull132** [comment]
Or a confirmation request by the subject?

**Comment by SoundScopes** [comment]
Confirmation unless on harm intent to give traitors the ability to be annoying?

**Comment by jack-fractal** [comment]
Errr... it does _remove_ your hair, but it doesn't permanently change the color. The color of your hair can be set by the spray cans, so a helpful roboticist should be able to fix you.

Delay on the sprayer is a good idea.
