### ISSUE TITLE
IPCs + Radiation storm

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora-Old#664]
![proof](http://puu.sh/iXOts/8f0a4a5a60.png)

This happened after a radiation storm with an IPC. The IPC's hulk gene was activated as they entered. I need to test properly whenever I get time, and see if it can be repeated.

**Comment by LikelyMeowness** [comment]
For the record, Duck did this with Braces, but with mutagen, so yes, it's likely easily replicable.

**Comment by SoundScopes** [comment]
I went and just removed the ability for them to be affected by random mutation changes in 
https://github.com/SoundScopes/Aurora/commit/9159ab35fff663044ef5865d4d6615e9bdb2d7a4
