### ISSUE TITLE
Shell bug - Applying synthetic skin does not update visual model.

### ISSUE THREAD

**Issue by Reyjakai** [Aurorastation/Aurora-Old#667]
This only happens after a part has been damaged. If the skin has been applied, however, damaging another body part will actually fix the other bodyparts. 

Before fixing damage, but after fixing skin: http://gyazo.com/c4e6a8108313b93625f47397b24662f4
Attacking myself somewhere else: http://gyazo.com/8568f8eb208f072858f165761bbd9fc6

Also it removes your hair completely when your head is changed. Is that something that can be fixed?

**Comment by jack-fractal** [comment]
Hey Rey! 

I can't quite replicate this bug. I'm not sure of the order of operations. It's probably got something to do with update_body, but I need exact steps to figure this out. Can you contact me over byond communicator? 

- Jack
