### ISSUE TITLE
Bug found, cloaking on a cargo tug

### ISSUE THREAD

**Issue by Lucifers-son** [Aurorastation/Aurora-Old#678]
If you use a chameleon projector while on a cargo tug, you cloak then you can move around anywhere, but when you un-cloak it will TP you back to where the cargo tug is.

**Comment by Zuhayr** [comment]
Cham projectors are entirely distinct from the cloaking code, just for clarity's sake. Cham projectors move you into an item and then move the item around via relaymove or something like that.
