### ISSUE TITLE
Bug with hairstyle

### ISSUE THREAD

**Issue by Sindroman** [Aurorastation/Aurora-Old#699]
Well, I have set my character preference for haricut: Gentle, beard: full beard. But instead that I spawned with Half Bald Hairfstyle and different beard everytime(haven't tried to change style to different and back). It happens 1 week ago, before it was fine.

**Comment by GlamourChariot** [comment]
Hey, that isn't actually a hairstyle in the game as far as I am aware. If you're still having this issue, can you please take a screenshot of your character customization screen so we can see your exact settings and test appropriately?
