### ISSUE TITLE
Ninja energy net is borked.

### ISSUE THREAD

**Issue by SenpaiShadow** [Aurorastation/Aurora-Old#701]
Even when you the power net disappears you are still trapped in it and can't move anymore.
We tried:
- Un/winding
- Buckled them to a rollerbed/wheelchair/body bag
- Put them in a scanner/sleeper/DNA modifier
- Disarming them.

Nothing worked. At the moment, once you are trapped in that thing you are out of the round since you can't do anything anymore except picking things up.

EDIT:
- Cloning worked

**Comment by LordFowl** [comment]
For further specifics, they cannot even be moved by other players, unless buckled into a roller bed/wheelchair/bodybag.  You also cannot initiate a grab on them.

Another related bug is that you can escape an energy net via a rollerbed/wheelchair/bodybag.

**Comment by SoundScopes** [comment]
I've caught the moving bug.
The other bug I know about but haven't coded a fix for yet

**Comment by SoundScopes** [comment]
This needs testing again as a possible fix was put in
