### ISSUE TITLE
The arrivals shuttle is not shielded from radiation storm events

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora-Old#707]

**Comment by W3bster** [comment]
+1 to this issue.

Spawned as IAA in arrivals shuttle, instantly got radiated.
Should be an easy fix. Is your arrivals shuttle simulated tiles?

**Comment by SoundScopes** [comment]
Simulated tiles are only power and atmos related.

Radiation storms are done by area tags.
