### ISSUE TITLE
Evidence Lockup Requires Holding Cell Access

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora-Old#710]
For some reason, the evidence lockup requires access to the holding cells, which investigative staff obviously does not have. I think it would make sense that the evidence lockup would be accessible to the staff that actually collects evidence, so maybe make it general brig access?

**Comment by SoundScopes** [comment]
They were given the wrong access requirement, at the moment it requires you have all access levels 2,4,66 which is brig timers, forensic lockers, detective access
