### ISSUE TITLE
PDA messages eaten went sent from AI PDA message log

### ISSUE THREAD

**Issue by FelisCorax** [Aurorastation/Aurora-Old#712]
I was sending several PDA messages to one person, so I opened up the AI pda message log and clicked on their name to send the messages after the first one. Sometimes it worked, sometimes the message was never received (and didn't appear in the log).

**Comment by SierraKomodo** [comment]
I've come across this issue myself, and found that it only does this if you click on the person's name of a message log where you sent the message to them. If you click there name on a log where you received the message, it sends the reply back to them properly.

**Comment by FelisCorax** [comment]
Sweet, I'll remember that for in the future.
