### ISSUE TITLE
Mapping issues/suggestions

### ISSUE THREAD

**Issue by W3bster** [Aurorastation/Aurora-Old#714]
- Cameras required in many hallways near firedoors. When cameras were mapped in, the firedoors were not taken in account. So when they are down, many areas are left blind.
- Missing light in front of robotics.
- AI Upload Access's default cell is not good enough to charge the cyborgs. Needs to be higher capacity from the start.
- Needless Kitchen Shutters button besides the actual working one.
- Medbay Quarantine shutters missing in Morgue, genetics. Potentially maint, if you're that extreme.
- Emergency Shuttle's kits are not well placed, making them stack on eachother, obstructing eachother from view. As well as not diverse enough kits.
-  Suggesting an extra NanoMed vendor East of the shuttle.
- Dorm 3 northen light does not work.

**Comment by W3bster** [comment]
- Certain blast doors at the Odin have a too low Explosives resistance, allowing people to C4 them. (Ex. Admin Armory)

**Comment by Wittme** [comment]
We have received your report and are reviewing it.

**Comment by W3bster** [comment]
Another small note. In security, the lockdown blast doors hide the actual airlock when said airlocks open, preventing people from interacting with doors in their open state. Said door is the Security one in the screenshot, right besides the Security Infirmary.

http://puu.sh/k98hK/d2e90f0b2c.png

**Comment by W3bster** [comment]
Another issue. In maintenance, certain racks (See, near gravi gen) has it's items under the rack.
