### ISSUE TITLE
MULE BOTS

### ISSUE THREAD

**Issue by madpredator** [Aurorastation/Aurora-Old#727]
The MULE Bots arent working very well.
- They do reach some destinations , some others just simply dont. (Medbay and janitor works for example) (Kitchen, botanist, bar dont reach)
- The command for returning home isnt working.
- When unlocking controls they dont show -messages when cutting cables or show the status

I would like them to be fixed since its an important thing for cargo doing delivery more efficient for the station.

**Comment by SierraKomodo** [comment]
If I recall something, someone mentioned the pathing wasn't updated with the map changes (I have no idea if that's the case or not, but might help)

**Comment by madpredator** [comment]
UPDATE: 

Just checked what you said SierraKomodo and decided to download the Aurora-Master maping/coding
I could see there was a problem of the map indeed, the locations arent updated, and some of them are unreacheable.  Like engineering there is a windoows blocking the entrance of Mulebot. Did the test removing the windoos and MULE bot worked.

http://puu.sh/ltRJf/bc48e9e0bc.jpg

This is a really easy fix, just need to move the Navigation Beacons to other places. Like "Bar" or Security entrance and change their location names. I believe there were most of them removed but some of them are still working such as QM#1#2#3#4 Janitor, Tool Storage, and Medbay.. Dont even need those stupid plastic flaps

Thank you
