### ISSUE TITLE
Syndicate rucksack's itemstate (and iconstate?) failed.

### ISSUE THREAD

**Issue by Zidanyia** [Aurorastation/Aurora-Old#739]
/obj/item/weapon/storage/backpack/syndie
    name = "syndicate rucksack"
    desc = "The latest in carbon fiber and red satin combat rucksack technology. Comfortable and tough!"
    icon_state = "syndiepack"

Appears as the default N/S-facing double-barreled shotgun sprite when slung over the back. Worst.

**Comment by Alberyk** [comment]
Same with the wizard bag.
