### ISSUE TITLE
Intellicarded AI can transmit using AI radio even when wireless is disabled

### ISSUE THREAD

**Issue by FelisCorax** [Aurorastation/Aurora-Old#741]
I was playing the AI when I was carded by nuke ops. They naturally didn't turn on my wireless, but, much to their distress, I was still able to use the AI radio prefixes as normal. Pretty sure this wasn't intended.

**Comment by Zidanyia** [comment]
I believe the wifi prevents you only from interfacing with surrounding systems, so that you don't doorcrush your thief.
