### ISSUE TITLE
Library Maintenance is mapped as Bar Maintenance

### ISSUE THREAD

**Issue by Serveris** [Aurorastation/Aurora-Old#764]
The maintenence tunnels of the Chapel, Library, and Crime Lab are mapped with Bar Maintenance overlays. An oversight in the security remap of several months ago, it would seem.  http://prntscr.com/91kggs

**Comment by skull132** [comment]
Both a code and mapping issue. Since bar maint doesn't exist anymore, it's an idea to just rebrand it through code.
