### ISSUE TITLE
Cargo Supply Shuttle disappears if you call, cancel, then call again

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora-Old#770]
As it says in the title.

Using the supply shuttle console, if you call the supply shuttle, cancel the launch, then call it again while docked at the Odin, it will launch as normal, dock with the station, then somewhere around 30 seconds to 1 minute later, the shuttle walls/floors disappear while the server still thinks it's docked, leaving behind the engines, conveyer belt, and leaving the airlocks open.

**Comment by madpredator** [comment]
Removing the "CANCEL" button would be a smart idea then
