### ISSUE TITLE
Fire Alarms

### ISSUE THREAD

**Issue by Gollentar** [Aurorastation/Aurora-Old#774]
Fire Alarm construction and deconstruction are borked; and their circuits don't exist on station.

**Comment by SierraKomodo** [comment]
Can you be a little more specific on 'borked'? What exactly does it do/not do that's incorrect?

**Comment by Gollentar** [comment]
They are deconstructable, they can be screwed open, and some weird thing
turned on and off with a multitool, but no further actions can be taken.

Their circuits are not available on station, and if I am remembering
correctly, I was unable to actually construct one even with the circuit,
Dea had to spawn/move the old fire alarm I was trying to deal with.
