### ISSUE TITLE
Legless people can't move at all, despite having arms they could use to crawl around.

### ISSUE THREAD

**Issue by TishinaStalker** [Aurorastation/Aurora-Old#799]

**Comment by LordFowl** [comment]
This isn't really a bug or issue, but rather a suggestion. There is no crawling for our codebase whatsoever.

**Comment by TishinaStalker** [comment]
Actually! Legless people used to be able to drag themselves. I know this because I usually play a legless janitor and I used to be able to drag myself around after people unbuckled me from my chair. Last night, turns out I couldn't anymore. I assume this was after whatever update made it so that unbuckling a legless person immediately makes them *scream and *collapse.

**Comment by LordFowl** [comment]
Then I again assume that feature was removed for whatever reason. Regardless of whether or not it is, I also say legless but armed people should be able to buckle themselves into chairs as well.
