### ISSUE TITLE
Defibrillators make people immortal

### ISSUE THREAD

**Issue by Concerned** [Aurorastation/Aurora-Old#803]
A defib hit on a naked dead nerd with a ghost in his body reduces oxyloss by 5 and, if they have more than -100 health, revives them.

Unfortunately, they then become immortal.

They can survive anything short of huskification or the severing of their head, shambling about in a horrifying parody of the crewmate they once were.

It's a cool feature, but the whole "brought back from death to suffer eternally" thing might be better suited to a traitor/cult item.

The case in question was a Skrell security officer with internal bleeding, who died of bloodloss and was defibrillated and dosed up to the gills with bicaridine, dylovene and dexalin and then survived all the way to 0% blood before being given the merciful gift of true death by his laser-armed brother. 

Very touching.

_Urist McZombie seizes up and falls limp, his eyes dead and lifeless..._
_Urist McZombie seizes up and falls limp, his eyes dead and lifeless..._
_Urist McZombie seizes up and falls limp, his eyes dead and lifeless..._
_Urist McZombie seizes up and falls limp, his eyes dead and lifeless..._
_Urist McZombie seizes up and falls limp, his eyes dead and lifeless..._
_Urist McZombie seizes up and falls limp, his eyes dead and lifeless..._

A recreation image is ![Night of the Living Skrell](https://i.gyazo.com/d194bd16ec1ead08373881c88c98e50e.png)

**Comment by skull132** [comment]
This may actually have to do with how a lack of blood is supposed to kill you. I will have to test.
