### ISSUE TITLE
Some ballistic weapons do not do enough damage to kill you if you stick it in your mouth and shoot

### ISSUE THREAD

**Issue by TishinaStalker** [Aurorastation/Aurora-Old#827]
These being: weapon/gun/shotgun/pump, Uzi, and Stetchkin.

For the shotgun, I made 100% sure to have a lethal shell loaded. It dealt 78.4 brute damage every time I tried.

**Comment by skull132** [comment]
Suicide by gun being unreliable, in my opinion, is actually quite good fun. I think it makes for pretty decent RP?

**Comment by LordFowl** [comment]
A shotgun is reliable enough to kill you. While handguns being perhaps unreliable is feasible, ballistic rifles and shotguns should always be lethal. Energy weaponry is another consideration.

**Comment by TishinaStalker** [comment]
A shotgun blast in your mouth would, without a doubt, kill you. Not really any ifs, ands or buts on that, really.

**Comment by Concerned** [comment]
This is old, but... there's plenty of cases of people trying to commit suicide, often with shotguns, and only succeeding in blowing a big chunk of their face off and giving themselves a lobotomy.

**Comment by Meowykins** [comment]
That's a bit off. I've done the same accidentally with a pump in-game, with non-lethal ammo and it killed me.
