### ISSUE TITLE
Power cells put into borgs that have higher capacity than "high-cap" are unable to be recharged in a cyborg charger

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora-Old#833]

**Comment by Ryan784** [comment]
Can you elaborate on what you mean by a higher capacity than "high-cap"? Or can you re-describe the events leading up to a Borg being unable to recharge in the cyborg charger?

**Comment by OneOneThreeEight** [comment]
It seems inconsistent, it's possible that being hit with an EMP affects this.

**Comment by Alberyk** [comment]
If I am not wrong, the ones that are printed at the protolathe aren't 100% reliable and can have this issue.
