### ISSUE TITLE
Mapping: Camera's networks in Atmos incorrectly configured

### ISSUE THREAD

**Issue by Ryan784** [Aurorastation/Aurora-Old#852]
Almost every single camera in Atmoshperics is incorrectly configured. They're all named "security camera" - which is fine, but they all have different networks (such as TCommsat, Anomaly, MINE, etc). Essentially, if the AI (or anyone) were to use the jump-to-network feature, it will plop them in atmospherics.

The camera's c_tags are also incorrectly set.

There is also another camera, right outside EVA named "security camera", this one too is incorrectly configured, with it's network being "MINE".

It's a pretty simple fix, just change the camera's networks to there relevant spots, "SS13" or "Engineering". (and fix their names, if you really want, but that isn't as important).

This would also fix issue #839.

**Comment by Wittme** [comment]
this issue is well known and is actually an issue station wide. It was caused by a former mapper that skull let on the team without trial. I will be doing a full camera overhaul after irl things settle down next week
