### ISSUE TITLE
Sleepy, sleepy IPCs

### ISSUE THREAD

**Issue by PrismaticGynoid** [Aurorastation/Aurora-Old#854]
If an IPC gets a sleeping effect, such as from an anomaly, the effect never goes away, and they are stuck with blurry vision, passing out every few seconds, for the rest of the round. I was only exposed to a fraction of this effect for 3 seconds, and I was effectively taken out of the round.

**Comment by OneOneThreeEight** [comment]
There's a massive plethora of bugs related to the "bad" effects of anomalies. I remember encountering this about a year ago.
