### ISSUE TITLE
Vaurca organ bug

### ISSUE THREAD

**Issue by SenpaiShadow** [Aurorastation/Aurora-Old#873]
A spawned Vaurca has unlimited "breathing apparatus" in their chest.
I removed 10 so far.

EDIT:
Also has unlimited "second heart"s in their chest.

**Comment by Ryan784** [comment]
Can you elaborate more on this? When I spawn in a /mob/living/carbon/human/bug I don't see what you mean.
https://gyazo.com/17e9115008948c8121b412e8927533fc

**Comment by SenpaiShadow** [comment]
Cut the bug open and start removing their organs. They have endless organs.
